### PR TITLE
fix: Invalid image reference format when using digest strategy with helm charts

### LINKED ISSUE #259: Digest is not working (Digest, Tag, Helm)
**Describe the bug**
argocd-image-updater: v0.10.3
argocd: v2.1.2
gitrepo: helm

Strategy
```
argocd-image-updater.argoproj.io/write-back-method: argocd
argocd-image-updater.argoproj.io/image-list: myimagealias=gcr.io/project-name/images-path/my-image-name:my-tag-name
argocd-image-updater.argoproj.io/myimagealias.update-strategy: digest

```

I'm using the digest strategy for image updating and from argocd-image-updater end all seems to work fine, and I'm getting the successfully updated message. Yet ArgoCD doesn't seem to update the image.

```
time="2021-09-16T19:47:35Z" level=info msg="Successfully updated the live application spec" application=dev-environment
```

When I check the Argo CD, I can see the following has been added to parameters, but it does't trigger an update.
```
image.name
  gcr.io/project-name/images-path/my-image-name
image.tag
 sha256:xxxxxxx
```

My approach / requirement is to have  argocd as the write-back method and only the team members updating the deployment repo with image details and repo tags per each environment.

1. Can anyone tell me what I might be doing wrong here?
2. Any help on fixing this issue is appreciated

### PR DESCRIPTION
**Pull request by ElArtista**
Fixes #259 #210

When using digest update strategy, the helm image.tag parameter now composes a full tag of both the tag and the digest in the form:
```
sometag@sha256:<somelonghashstring>
```
This avoids invalid references in almost all helm charts that construct the image ref as `image.repository:image.tag`, that so far resulted to the invalid references of the form:
```
some/image:sha256:<somelonghashstring>
```

### CODE REVIEW

File: pkg/image/image.go [hunk 1]
```diff
@@ -105,6 +105,24 @@ func (img *ContainerImage) GetFullNameWithTag() string {
 	return str
 }
 
+// GetFullTag returns tag name along with any tag digest set for the image
+func (img *ContainerImage) GetFullTag() string {
```
Comment (jannfis) [inline pkg/image/image.go:109]: Can we please rename this to something more precise, e.g. `GetTagWithDigest()`?

**Review by jannfis — CHANGES_REQUESTED** [review]
Thanks a lot, @ElArtista - this is useful!

I only have one cosmetic concern, please see below.

Also, can you please provide unit tests for the method?

File: pkg/image/image.go (hunk 1 above)
Comment (ElArtista) [reply pkg/image/image.go:109]: Will do immediately!

Comment (ElArtista) [reply pkg/image/image.go]: Done.

**Comment by ElArtista** [comment]
Added unit tests, I believe this is now ready!

**Review by jannfis — APPROVED** [review]
LGTM. Thanks a lot @ElArtista !

**Comment by dwi-mfbcs** [comment]
Waiting for this fix to be released. Do we have an ETA for a release that will include this fix? Thanks.
