### PR TITLE
fix: set leader node only when cache is warmed

### LINKED ISSUE #1368: Image Updater v1.0.1 stucks in "Running" with failing health checks / leader election never succeeds
## **Description**

When deploying **Argo CD Image Updater v1.0.1**, the pod becomes stuck in the *Running* phase but never becomes *Ready*.
The health probe continuously fails, and the controller never completes startup.

This occurs both:

* when restarting the Image Updater deployment, and
* when running **more than 1 replica** (leader election appears to stall).

## **Logs**

```
time="2025-11-26T09:19:49Z" level=info msg="Controller runtime logger initialized." controller=imageupdater controllerGroup=argoproj.io
time="2025-11-26T09:19:49Z" level=info msg=starting app="argocd-image-updater: v1.0.1+cc39181"
time="2025-11-26T09:19:49Z" level=info msg="webhook server is disabled"
time="2025-11-26T09:19:49Z" level=info msg="starting manager"
I1126 09:19:49.918949       1 leaderelection.go:257] attempting to acquire leader lease argocd-image-updater-system/c21b75f2.argoproj.io...
time="2025-11-26T09:20:01Z" level=info msg="healthz check failed" statuses="[{}]"
time="2025-11-26T09:20:11Z" level=info msg="healthz check failed" statuses="[{}]"
...
(repeats indefinitely)
```

The pod stays running indefinitely with logs repeating:

```
healthz check failed: statuses="[{}]"
```

and the deployment never reaches a Ready state.

## **Expected Behavior**

* Image Updater should start successfully
* Health check should return healthy
* Leader election should succeed even when running 2+ replicas

## **Actual Behavior**

* Health check always fails
* Controller never becomes ready
* Leader election never completes
* Running more than 1 replica makes the issue even more consistent (every pod gets stuck)

## **Steps to Reproduce**

1. Install Argo CD Image Updater v1.0.1 (Helm or manifests)
2. Restart the deployment
   **OR**
3. Scale replicas to 2+
4. Observe that the pods stay Running but never become Ready
5. Logs show repeated `healthz check failed` messages

### PR DESCRIPTION
**Pull request by dkarpele**
Closes #1368 

## Summary by CodeRabbit

* **Chores**
  * Added leader-awareness to readiness: readiness now depends on leadership and cache warm state, so only the elected leader requires a warmed cache to report ready.
  * Exposed a signal indicating the component should run only on the leader replica.
* **Tests**
  * Added coverage exercising readiness behavior across leader/non-leader and warmed/not-warmed scenarios.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: cmd/run_test.go [hunk 1]
```diff
@@ -340,3 +341,68 @@ func TestReadyzCheckWithWarmupStatus(t *testing.T) {
 		assert.Equal(t, "cache is not yet warmed", err.Error())
 	})
 }
+
+// Assisted-by: Gemini AI
```
Comment (anishbista60) [inline cmd/run_test.go:345]: I am not maintainer or reviewer but seeing this line, Is your honesty or any policy standard ?

Comment (dkarpele) [reply cmd/run_test.go:345]: There is no shame in using AI responsibly. There is a common practice to explicitly mark parts of code or the whole commit with annotation. You can read more for example [here](https://www.redhat.com/en/blog/ai-assisted-development-and-open-source-navigating-legal-issues). I found AI very useful in unit testing assistance and docstrings generation.

Comment (anishbista60) [reply cmd/run_test.go:345]: I really like this initative of RedHat.

**Review by chengfang — APPROVED** [review]
