### PR TITLE
Initialize the kubeClient and applicationsClientSet correctly

### LINKED ISSUE #1021: Not starting up due to memory violation or nil pointer exception
**Describe the bug**
After a restart of the k3s cluster, I'm unable to start up the `argocd-image-update` due to a memory or nil pointer issue.
Before it was running for month without any issue.

**To Reproduce**

1. Deploy default `Application` with no additional settings in the same namespace as you are running your ArgoCD instance
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj-labs/argocd-image-updater.git
    path: manifests
    directory:
      include: install.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
```

**Expected behavior**

- Clean startup without memory violation or nil pointer exception

**Additional context**

- It's a single node k3s cluster which has been restarted due to an increase (Proxmox VM) of
  - local LVM volume (`/`)
  - add more memory
- No other workloads or system service are affected

**Version**
Please tell us about the version you encountered the issue with

- Image: `quay.io/argoprojlabs/argocd-image-updater:latest`
- ArgoCD: `quay.io/argoproj/argocd:v2.13.3`

**Logs**
```txt
time="2025-01-26T09:44:10Z" level=info msg="argocd-image-updater v99.9.9+980eff5 starting [loglevel:INFO, interval:2m0s, healthport:8080]"
time="2025-01-26T09:44:10Z" level=warning msg="commit message template at /app/config/commit.template does not exist, using default"
time="2025-01-26T09:44:10Z" level=warning msg="Registry configuration at /app/config/registries.conf could not be read: stat /app/config/registries.conf: no such file or directory -- using default configuration"
time="2025-01-26T09:44:10Z" level=info msg="ArgoCD configuration: [apiKind=kubernetes, server=argocd-server.argocd, auth_token=false, insecure=false, grpc_web=false, plaintext=false]"
time="2025-01-26T09:44:10Z" level=info msg="Starting health probe server TCP port=8080"
time="2025-01-26T09:44:10Z" level=info msg="Starting metrics server on TCP port=8081"
time="2025-01-26T09:44:10Z" level=info msg="Warming up image cache"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x22f71b4]

goroutine 1 [running]:
github.com/argoproj-labs/argocd-image-updater/pkg/argocd.(*k8sClient).ListApplications(0x300000002?, {0x0, 0x0})
    /src/argocd-image-updater/pkg/argocd/argocd.go:64 +0x34
main.runImageUpdater(0xc00072cdc0, 0x1)
    /src/argocd-image-updater/cmd/run.go:270 +0x159
main.warmupImageCache(0xc00072cdc0)
    /src/argocd-image-updater/cmd/run.go:365 +0x3e
main.newRunCommand.func1(0xc00011f000?, {0x2a03427?, 0x4?, 0x2a0342b?})
    /src/argocd-image-updater/cmd/run.go:153 +0xd73
github.com/spf13/cobra.(*Command).execute(0xc000227808, {0x47c0ac0, 0x0, 0x0})
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000227508)
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
    /go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.newRootCommand()
    /src/argocd-image-updater/cmd/main.go:65 +0x1b4
main.main()
    /src/argocd-image-updater/cmd/main.go:82 +0x4e
stream closed EOF for argocd/argocd-image-updater-bccb9d7d7-72bpg (argocd-image-updater)
```

### PR DESCRIPTION
**Pull request by ishitasequeira**
Initialize the kubeClient and applicationsClientSet correctly

Fixes #1021

### CODE REVIEW

File: cmd/util.go [hunk 1]
```diff
@@ -28,30 +30,37 @@ func getPrintableHealthPort(port int) string {
...
-	if fullKubeConfigPath != "" {
-		log.Debugf("Creating Kubernetes client from %s", fullKubeConfigPath)
-	} else {
-		log.Debugf("Creating in-cluster Kubernetes client")
+	clientset, err := kubernetes.NewForConfig(config)
+	if err != nil {
+		return nil, err
 	}
 
-	kubernetesClient, err := registryKube.NewKubernetesClientFromConfig(ctx, namespace, fullKubeConfigPath)
```
Comment (chengfang) [inline cmd/util.go:48]: Now that the above func `registryKube.NewKubernetesClientFromConfig()` is not used anymore, do we still need this func in registry-scanner?  See https://github.com/argoproj-labs/argocd-image-updater/blob/master/registry-scanner/pkg/kube/kubernetes.go#L33

File: cmd/util.go [hunk 2]
```diff
@@ -28,30 +30,37 @@ func getPrintableHealthPort(port int) string {
...
 	}
 
-	if fullKubeConfigPath != "" {
-		log.Debugf("Creating Kubernetes client from %s", fullKubeConfigPath)
-	} else {
-		log.Debugf("Creating in-cluster Kubernetes client")
+	clientset, err := kubernetes.NewForConfig(config)
+	if err != nil {
+		return nil, err
 	}
```
Comment (chengfang) [inline cmd/util.go:56]: Wondering if we should move these creation logic back to https://github.com/argoproj-labs/argocd-image-updater/blob/master/pkg/kube/kubernetes.go, which holds some other related functions.

Comment (ishitasequeira) [reply cmd/util.go:56]: That is a good idea. I will move it to the package.

File: cmd/util.go (hunk 1 above)
Comment (ishitasequeira) [reply cmd/util.go:48]: I think we should keep this even if not being used, especially because this might be used by other clients who only use registry-scanner.

**Review by chengfang — APPROVED** [review]
