### PR TITLE
fix: resolve unauthorized error when listing ACR tags with scope map token

### LINKED ISSUE #1502: Authentication error (unauthorized) when listing tags in ACR using Scope Map token
**Describe the bug**
When accessing Azure Container Registry (ACR) using a Scope Map token in ArgoCD Image Updater, an authentication error occurs when listing tags.

ArgoCD Image Updater fetches an Access Token via Basic Auth using the `pull` scope to call the tag list API. However, ACR explicitly requires the `metadata.read` (or `metadata_read`) scope to list tags. Because Image Updater hardcodes the scope to `pull`, passing only this scope results in a `denied`/`unauthorized` error from the registry.

**To Reproduce**

1. Configure ArgoCD Image Updater to monitor an image hosted on Azure Container Registry (ACR).
2. Configure authentication using an ACR Scope Map token (which restricts specific permissions).
3. Trigger ArgoCD Image Updater to check for new image tags.
4. Observe the Image Updater logs. It fails to fetch tags with a `denied: requested access to the resource is denied` error.

**Expected behavior**
ArgoCD Image Updater should successfully authenticate and retrieve the tag list from ACR. This requires the requested scope to either include `metadata.read` (e.g., `metadata_read,pull` for ACR) or be configurable, rather than being hardcoded to `pull`.

**Additional context**
Related Issue #473 
I verified this behavior manually using `curl`. When fetching the Access Token with the `metadata_read,pull` scope, the API call works perfectly.

*1. Basic Auth Reproduction (Failing with only `pull`):*

```
curl -s -u "{USERNAME}:{PASSWORD}" "https://{REGISTRY}.azurecr.io/oauth2/token?service={REGISTRY}.azurecr.io&scope=repository:{IMAGE}:pull"
# Returns: {"access_token":"{ACCESS_TOKEN}"}
```

```
curl -H "Authorization: Bearer {ACCESS_TOKEN}" https://{REGISTRY}.azurecr.io/v2/{IMAGE}/tags/list
# Returns: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required...","detail":[{"Type":"repository","Name":"{IMAGE}","Action":"metadata_read"}]}]}
```

*2. Basic OAuth Reproduction (Succeeding with `metadata_read,pull`):*

```
curl -s -u "{USERNAME}:{PASSWORD}" "https://{REGISTRY}.azurecr.io/oauth2/token?service={REGISTRY}.azurecr.io&scope=repository:{IMAGE}:metadata_read,pull"
# Returns: {"access_token":"{ACCESS_TOKEN}"}
```

```
curl -H "Authorization: Bearer {ACCESS_TOKEN}" https://{REGISTRY}.azurecr.io/v2/{IMAGE}/tags/list
# Returns: {"name":"{IMAGE}","tags":["{TAG}"
```

*3. Current Code Analysis:*
The issue is caused by the `pull` scope being hardcoded as a string in the Basic Auth token retrieval code.

```
// NewRepository is a wrapper for creating a registry client that is possibly
// rate-limited by using a custom HTTP round tripper method.
func (clt *registryClient) NewRepository(nameInRepository string) error {
	// ... (omitted for brevity)
	authTransport := transport.NewTransport(
		clt.endpoint.GetTransport(), auth.NewAuthorizer(
			challengeManager1,
			// "pull" is hardcoded here 👇
			auth.NewTokenHandler(clt.endpoint.GetTransport(), clt.creds, nameInRepository, "pull"),
			auth.NewBasicHandler(clt.creds)))
    // ...
}
```

**Proposal:** If the maintainers agree that this is a bug, I would love to submit a Pull Request to fix it. A potential fix could involve allowing registry-specific scopes (like `pull,metadata.read` for ACR) or making the requested scope configurable.

**Version**`v1.0.5`

**Regression**
Does this issue apply to (check all that apply):

- [ ]  Annotation-based configuration (versions starting with `0`, e.g., `0.17.0`)
- [x]  CRD-based configuration (versions starting with `1`, e.g., `1.0.0`)

**Latest working version (if applicable)**
N/A (Likely an ongoing architectural limitation with ACR Scope Map tokens due to the hardcoded scope).

**Logs**

```
level=trace msg="Performing HTTP GET https://${REGISTRY}.azurecr.io/v2/${REGISTRY}/tags/list"
level=info msg="Processing results: applications=1 images_considered=1 images_skipped=0 images_updated=0 errors=1"
level=error msg="Could not get tags from registry: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.\n" alias=${ALIAS} application=${APPLICATION} image_name=${IMAGE} image_tag=${TAG} registry=${REGISTRY}.azurecr.io
```

### PR DESCRIPTION
**Pull request by RyuKwanKon**
Fixes #1502

`registryClient.NewRepository()` previously hardcoded the `"pull"` action when requesting an access token via `auth.NewTokenHandler()`. When accessing Azure Container Registry (ACR) using strict Scope Map tokens, ACR explicitly requires the `metadata_read` scope to list image tags. Because only `"pull"` was requested, ACR returned a `denied/unauthorized` error.

Now dynamically determines the required token actions based on the registry endpoint:

- Added `getTokenActions(registryAPI)` to evaluate the target registry.
- If the endpoint is ACR (`.azurecr.io`), it now requests `pull`, `metadata_read`, and `content_read`.
- All other registries default to `pull`, preserving existing behavior.
- Passed the dynamically generated `actions...` to `auth.NewTokenHandler()`.

Also includes comprehensive unit tests (`TestNewRepository_ACR_Actions`) with a mock HTTP server to validate that the correct scopes are requested during the OAuth2 token challenge for both ACR and non-ACR endpoints.

**Note:** This is a safe, backwards-compatible change. It specifically targets `.azurecr.io` domains to fix the ACR tag listing issue without affecting other container registries (Docker Hub, GHCR, Quay, etc.) which will continue to use the standard `"pull"` scope.

## Summary by CodeRabbit

* **New Features**
  * Registry authentication now requests context-aware permission scopes: Azure Container Registry endpoints request pull, metadata_read, and content_read; other registries request pull-only.

* **Tests**
  * Added integration-style tests that simulate token server interactions to verify ACR vs non-ACR token scope requests.

### CODE REVIEW

File: registry-scanner/pkg/registry/client_test.go [hunk 1]
```diff
@@ -45,6 +47,111 @@ func TestBasic(t *testing.T) {
...
+
+		require.NotNil(t, capturedTokenRequest, "Token request should have been captured")
+
+		scope := capturedTokenRequest.URL.Query().Get("scope")
+		assert.Contains(t, scope, "pull")
+		assert.NotContains(t, scope, "metadata_read", "Non-ACR endpoint should not request metadata_read")
+		assert.NotContains(t, scope, "content_read", "Non-ACR endpoint should not request content_read")
+	})
+
+	t.Run("Non-ACR endpoint NewRepository with mock server - only pull", func(t *testing.T) {
```
Comment (chengfang) [inline registry-scanner/pkg/registry/client_test.go]: This subtest seems to be a subset of the previous one. If so, can we just remove this subtest?

File: registry-scanner/pkg/registry/client_test.go [hunk 2]
```diff
@@ -45,6 +47,111 @@ func TestBasic(t *testing.T) {
...
+
+	t.Run("Non-ACR endpoint triggers token request with only pull action", func(t *testing.T) {
+		// Mock registry server that simulates /v2/ ping with Bearer challenge
+		var capturedTokenRequest *http.Request
+		var serverURL string
+
+		mux := http.NewServeMux()
+		mux.HandleFunc("/v2/", func(w http.ResponseWriter, r *http.Request) {
+			w.Header().Set("WWW-Authenticate",
+				fmt.Sprintf(`Bearer realm="%s/oauth2/token",service="myacr.azurecr.io"`, serverURL))
```
Comment (chengfang) [inline registry-scanner/pkg/registry/client_test.go]: why is `myacr.azurecr.io` in the above Non-ACR subtest?

File: registry-scanner/pkg/registry/client_test.go (hunk 1 above)
Comment (RyuKwanKon) [reply registry-scanner/pkg/registry/client_test.go]: You're right, this subtest is redundant. The previous subtest already covers the same mock server setup and NewRepository call, with the additional token scope verification.

File: registry-scanner/pkg/registry/client_test.go (hunk 2 above)
Comment (RyuKwanKon) [reply registry-scanner/pkg/registry/client_test.go]: @chengfang  Since getTokenActions() determines ACR vs non-ACR based on the registry URL, the myacr.azurecr.io in the WWW-Authenticate header has no effect when mockServer.URL is 127.0.0.1. The test name and header value make it look like an ACR test, but it actually exercises the non-ACR  path. I'll rename the subtest to clarify it's non-ACR and change the service value to something neutral like "mock-registry".
